services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:v0.14.4-debug
    container_name: openobserve
    restart: always
    ports:
      - "5080:5080"
      - "5081:5081"
    environment:
      ZO_ROOT_USER_EMAIL: "${OPENOBSERVE_USER_EMAIL:-root@example.com}"
      ZO_ROOT_USER_PASSWORD: "${OPENOBSERVE_USER_PASSWORD:-Complexpass#123}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5080/healthz"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  otel-collector:
    image: otel/opentelemetry-collector:0.121.0
    container_name: otel-collector
    restart: always
    ports:
      - "4317:4317"
      - "13133:13133"
    volumes:
      - ./otel-collector-config.yaml:/etc/config.yaml
    environment:
      OPENOBSERVE_HOST: "openobserve"
      OPENOBSERVE_PORT: "5081"
      OPENOBSERVE_AUTH: "cm9vdEBleGFtcGxlLmNvbTpDb21wbGV4cGFzcyMxMjM="
      OTEL_COLLECTOR_GRPC_PORT: "4317"
      OTEL_COLLECTOR_HEALTH_CHECK_ENDPOINT: "0.0.0.0:13133"
    command: ["--config=/etc/config.yaml"]
    depends_on:
      openobserve:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:13133/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
