receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  otlp/openobserve:
    endpoint: ${env:OPENOBSERVE_ENDPOINT}
    headers:
      Authorization: "Basic ${env:OPENOBSERVE_AUTH}"
      organization: ${env:OPENOBSERVE_ORG}
      stream-name: default
    tls:
      insecure: false

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/openobserve]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/openobserve]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/openobserve]
