receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:${env:OTEL_COLLECTOR_GRPC_PORT}

processors:
  batch:

exporters:
  debug:
  otlp/openobserve:
    endpoint: "${env:OPENOBSERVE_HOST}:${env:OPENOBSERVE_PORT}"
    headers:
      Authorization: "Basic ${env:OPENOBSERVE_AUTH}"
      organization: default
      stream-name: default
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/openobserve]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/openobserve]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/openobserve]
