receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:${env:OTEL_COLLECTOR_GRPC_PORT}

processors:
  batch:

exporters:
  otlp/openobserve:
    endpoint: "${env:OPENOBSERVE_HOST}:${env:OPENOBSERVE_PORT}"
    headers:
      Authorization: "Basic ${env:OPENOBSERVE_AUTH}"
      organization: default
      stream-name: default
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: "${env:OTEL_COLLECTOR_HEALTH_CHECK_ENDPOINT}"

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/openobserve]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/openobserve]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/openobserve]
